// Code generated by mockery v2.6.0. DO NOT EDIT.

package dbevent

import mock "github.com/stretchr/testify/mock"

// MockBackoffer is an autogenerated mock type for the Backoffer type
type MockBackoffer struct {
	mock.Mock
}

// ResetSleepBackoff provides a mock function with given fields:
func (_m *MockBackoffer) ResetSleepBackoff() {
	_m.Called()
}

// SleepBackoff provides a mock function with given fields:
func (_m *MockBackoffer) SleepBackoff() {
	_m.Called()
}
